### ISSUE TITLE
about优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/about#13]
## 签约作者墙
<img width="299" alt="image" src="https://user-images.githubusercontent.com/8476969/216015887-6461216a-a099-4ac8-a1a2-7f406294aec4.png">

**Comment by iRuxu** [comment]
## 设计资源
字体，矢量图等

**Comment by iRuxu** [comment]
## 盒子娘
盒子娘设定页面等

**Comment by nierssaxa** [comment]
> ## 签约作者墙
> <img alt="image" width="299" src="https://user-images.githubusercontent.com/8476969/216015887-6461216a-a099-4ac8-a1a2-7f406294aec4.png">

https://www.figma.com/file/IzqKIAi28VG7ux5S61KwKK/JX3BOX-ABOUT-US?node-id=0%3A1&t=OYOFzThzioRIqCsP-1

**Comment by iRuxu** [comment]
注意直接代码上 直接起新的view vue和css
